from . import crud_teacher
from . import crud_class
from . import crud_subject
from . import crud_assignment
from . import crud_settings
from . import crud_timetable
from . import crud_system
from . import crud_class_subject_constraint
from . import crud_saved_timetable
